Document: shotdetect
Title: Debian shotdetect Manual
Author: <insert document author here>
Abstract: This manual describes what shotdetect is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/shotdetect/shotdetect.sgml.gz

Format: postscript
Files: /usr/share/doc/shotdetect/shotdetect.ps.gz

Format: text
Files: /usr/share/doc/shotdetect/shotdetect.text.gz

Format: HTML
Index: /usr/share/doc/shotdetect/html/index.html
Files: /usr/share/doc/shotdetect/html/*.html

  
